---
title: "Hand Extracted Feature Stats"
author: "Helen Gent"
date: "9/23/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(tidyverse)
```

```{r}
global = read.csv("~/Desktop/Irony-Recognition/FeaturalAnalysis/handExtracted/global_measures.csv")
f0_sequential = read.csv("~/Desktop/Irony-Recognition/FeaturalAnalysis/handExtracted/sequential_measures.csv")
```

```{r}
durPlot = ggplot(data = global,aes(speaker, duration, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "Duration", color = "Label")

durPlot

hnrPlot = ggplot(data = global,aes(speaker, hnr, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "hnr", color = "Label")

hnrPlot

meanF0Plot = ggplot(data = global,aes(speaker, f0globalMean, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "Mean F0", color = "Label")

meanF0Plot

sdF0Plot = ggplot(data = global,aes(speaker, f0globalSD, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "F0 sd", color = "Label")

sdF0Plot

avgPausePlot = ggplot(data = global,aes(speaker, avgPauseLength, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "Average Pause Length", color = "Label")

avgPausePlot

s2sPlot = ggplot(data = global,aes(speaker, sound2silenceRatio, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "Sound to Silence Ratio", color = "Label")

s2sPlot

totalPausePlot = ggplot(data = global,aes(speaker, totalPauses, color=label))+geom_boxplot()+labs(title = " ", x = "Speaker", y = "Total number of Pauses", color = "Label")

totalPausePlot
```

