---
title: "PCA glmm"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(stringr)
require(mgcv)
require(devtools)
require(itsadug)
require(tidyverse)
require(lme4)
require(lmerTest)
require(MuMIn)
require(sjPlot)
require(Rcpp)
library(dplyr)
library(plot3D)
library(pROC)

library(cvms)
```


```{r}
setwd("C:/Users/Helen/Desktop/Stats/Pruned3_big")

pcaData = read.csv("3factorPCA.csv")
```
Let's try removing outliers
```{r}
PC1mean = mean(pcaData$PC1)
PC1sd = sd(pcaData$PC1)
PC2mean = mean(pcaData$PC2)
PC2sd = sd(pcaData$PC2)
PC3mean = mean(pcaData$PC3)
PC3sd = sd(pcaData$PC3)

pcaData = filter(pcaData, PC1 >= PC1mean - (2.5 * PC1sd))
pcaData = filter(pcaData, PC1 <= PC1mean + (2.5 * PC1sd))
pcaData = filter(pcaData, PC2 >= PC2mean - (2.5 * PC2sd))
pcaData = filter(pcaData, PC2 <= PC2mean + (2.5 * PC2sd))
pcaData = filter(pcaData, PC3 >= PC3mean - (2.5 * PC3sd))
pcaData = filter(pcaData, PC3 <= PC3mean + (2.5 * PC3sd))

```


```{r}
pcaData$speaker = as.factor(pcaData$speaker)

m3 = glmer(label ~ PC1 + PC2 + PC3 + (1|speaker), data = pcaData, family=binomial)

r.squaredGLMM(m3)

```


```{r}
summary(m3)
coefs = coef(m3)
coefs
exp(coefs$speaker)
```
```{r}
pcaData$m3Fit = predict(m3, type="response")
iData = filter(pcaData, label==1)
nData = filter(pcaData, label==0)
```

```{r}
m3Plot1 = scatter3D(pcaData$PC1, pcaData$PC2, pcaData$PC3, phi = 0, theta = 0, bty="g", 
                   colvar=pcaData$m3Fit, col=ramp.col(c("green", "blue")),
                   main = "Probability of predicting Ironic Label by First Three PCs", 
                   xlab = "PC1", ylab = "PC2", zlab = "PC3")
m3plot2 = scatter3D(pcaData$PC1, pcaData$PC2, pcaData$PC3, phi = 0, theta = 60,  bty="g",
                    colvar=pcaData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label by First Three PCs", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
m3Plot3 = scatter3D(pcaData$PC1, pcaData$PC2, pcaData$PC3, phi = 0, theta = 120,  bty="g",
                    colvar=pcaData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label by First Three PCs", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
m3Plot4 = scatter3D(pcaData$PC1, pcaData$PC2, pcaData$PC3, phi = 0, theta = 180,  bty="g",
                    colvar=pcaData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label by First Three PCs", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")

```

#Plotting only ironic samples
```{r}
iPlot1 = scatter3D(iData$PC1, iData$PC2, iData$PC3, phi = 0, theta = 0,  bty="g",
                   colvar=iData$m3Fit, col=ramp.col(c("green", "blue")),
                   main = "Probability of predicting Ironic Label 
                   by First Three PCs (Ironic)", 
                   xlab = "PC1", ylab = "PC2", zlab = "PC3") 
iPlot2 = scatter3D(iData$PC1, iData$PC2, iData$PC3, phi = 0, theta = 60,  bty="g",
                    colvar=iData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
iPlot3 = scatter3D(iData$PC1, iData$PC2, iData$PC3, phi = 0, theta = 120,  bty="g",
                    colvar=iData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
iPlot4 = scatter3D(iData$PC1, iData$PC2, iData$PC3, phi = 0, theta = 180,  bty="g",
                    colvar=iData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
```

Plotting only non-ironic samples
```{r}
nPlot1 = scatter3D(nData$PC1, nData$PC2, nData$PC3, phi = 0, theta = 0,  bty="g",
                   colvar=nData$m3Fit, col=ramp.col(c("green", "blue")),
                   main = "Probability of predicting Ironic Label 
                   by First Three PCs (Non-Ironic)", 
                   xlab = "PC1", ylab = "PC2", zlab = "PC3") 
nPlot2 = scatter3D(nData$PC1, nData$PC2, nData$PC3, phi = 0, theta = 60,  bty="g",
                    colvar=nData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Non-Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
nPlot3 = scatter3D(nData$PC1, nData$PC2, nData$PC3, phi = 0, theta = 120,  bty="g",
                    colvar=nData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Non-Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
nPlot4 = scatter3D(nData$PC1, nData$PC2, nData$PC3, phi = 0, theta = 180,  bty="g",
                    colvar=nData$m3Fit, col=ramp.col(c("green", "blue")), 
                    main = "Probability of predicting Ironic Label 
                   by First Three PCs (Non-Ironic)", 
                    xlab = "PC1", ylab = "PC2", zlab = "PC3")
```

Fresh model trained on 80% of the data and tested on 20% to get ROC curve

Remove model predictions from original data
```{r}
pcaData = select(pcaData, -m3Fit)
```

Train/test split
```{r}
smp_size = floor(0.80 * nrow(pcaData))

set.seed(6)
train_ind = sample(seq_len(nrow(pcaData)), size = smp_size)

trainData = pcaData[train_ind, ]
testData = pcaData[-train_ind, ]
```

Train fresh model on training data
```{r}
#all effects without interaction term
m4 = glmer(label ~ PC1 + PC2 + PC3 + (1|speaker), 
           data = trainData, family=binomial)
```

Calculate predictions from test data
```{r}
testData$m4pred = predict(m4, testData, type="response")
```


```{r}
test_roc = roc(testData$label ~ testData$m4pred, plot = TRUE, print.auc = TRUE)
```

```{r}
eval = evaluate(testData, target_col = "label", 
                prediction_cols = "m4pred", type = "binomial")
cm = eval$`Confusion Matrix`[[1]]

cm$Prediction = c("N", "I", "N", "I")
cm$Target = c("N", "N", "I", "I")

eval
plot_confusion_matrix(cm)
```

